[package]
name = "task"
version = "0.1.0"
authors = ["Will Fuqua <wafuqua@gmail.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "0.8"

[dependencies]
clap = "2"
serde = "0.8"
serde_json = "0.8"
regex = "0.1"
